// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1YL2rVIW8ePHHDo1TjjKh0c4Ur2Tpxk',
    appId: '1:92233708432:web:14a5e9fea9263913133915',
    messagingSenderId: '92233708432',
    projectId: 'laptopharbor-1fbf1',
    authDomain: 'laptopharbor-1fbf1.firebaseapp.com',
    storageBucket: 'laptopharbor-1fbf1.firebasestorage.app',
    measurementId: 'G-2TFW896YD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrYSx-sotCxQTzQ-8o_O9y_We3VJjXj0',
    appId: '1:92233708432:android:d4a54a7e8c69411b133915',
    messagingSenderId: '92233708432',
    projectId: 'laptopharbor-1fbf1',
    storageBucket: 'laptopharbor-1fbf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANAP12Ma8Wn97rWLAvvkb0LZPzn56yyio',
    appId: '1:92233708432:ios:d75f971a82fbd0c4133915',
    messagingSenderId: '92233708432',
    projectId: 'laptopharbor-1fbf1',
    storageBucket: 'laptopharbor-1fbf1.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANAP12Ma8Wn97rWLAvvkb0LZPzn56yyio',
    appId: '1:92233708432:ios:d75f971a82fbd0c4133915',
    messagingSenderId: '92233708432',
    projectId: 'laptopharbor-1fbf1',
    storageBucket: 'laptopharbor-1fbf1.firebasestorage.app',
    iosBundleId: 'com.example.laptopHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1YL2rVIW8ePHHDo1TjjKh0c4Ur2Tpxk',
    appId: '1:92233708432:web:1738a795dbb99875133915',
    messagingSenderId: '92233708432',
    projectId: 'laptopharbor-1fbf1',
    authDomain: 'laptopharbor-1fbf1.firebaseapp.com',
    storageBucket: 'laptopharbor-1fbf1.firebasestorage.app',
    measurementId: 'G-5CH836M6ME',
  );
}
